tasks:
  - init: . /home/gitpod/.sdkman/bin/sdkman-init.sh
  - command: sdk uninstall java 11.0.9.fx-zulu
  - command: sdk install java 11.0.10.hs-adpt
  - command: sdk install java 8.0.282-open
  - command: ./gradlew build
